{% set name = "mcfly" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cantino/mcfly/archive/v{{ version }}.tar.gz
  sha256: bfb6ca73c6a03047e3c61edf2b3c770e24ddbb0720e2a7dad3ea13a759572bb6

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - mcfly --help

about:
  home: https://github.com/cantino/mcfly
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Fly through your shell history
  dev_url: https://github.com/cantino/mcfly

extra:
  recipe-maintainers:
    - danielnachun
